version: '3.7'

services:
  # --- Orthanc Service (Unchanged) ---
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc_test # Optional: Give it a fixed name
    ports:
      - "11112:4242"  # DICOM port (Host:Container)
      - "8042:8042"   # Web UI (Host:Container)
    environment:
      - ORTHANC__NAME=ORTHANC_TEST
      - ORTHANC__DICOM_SERVER_ENABLED=true
      - VERBOSE_ENABLED=true
      - ORTHANC__DICOM_SERVER_ALWAYS_ALLOW_ECHO=true
      - ORTHANC__DICOM_SERVER_ALWAYS_ALLOW_FIND=true
      - ORTHANC__DICOM_SERVER_ALWAYS_ALLOW_MOVE=true
      - ORTHANC__DICOM_SERVER_ALWAYS_ALLOW_STORE=true
      - ORTHANC__DICOM_SERVER_VERIFY_CALLED_AET=false
    volumes:
      - orthanc_db:/var/lib/orthanc/db
    restart: unless-stopped

  # --- DCM4CHEE Archive Stack ---
  # Archive Application (replaces the old dcm4chee service)
arc:
    image: dcm4che/dcm4chee-arc-psql:5.33.1 # Use the specific tag
    container_name: dcm4chee_arc_test
    ports:
      - "11113:11112"
      - "8081:8080"
    environment:
      # --- Add this line ---
      - WILDFLY_WAIT_FOR=ldap:389 db:5432 # Tells arc to wait for ldap and db ports
      # --- Existing variables ---
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pacsdb
      - POSTGRES_USER=pacs
      - POSTGRES_PASSWORD=pacs
      - LDAP_URL=ldap://ldap:389
      - LDAP_BASE_DN=dc=dcm4che,dc=org
      - LDAP_ROOTPASS=secret
      - WILDFLY_ADMIN_USER=admin
      - WILDFLY_ADMIN_PASSWORD=admin
      - JAVA_OPTS=-Xms64m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
    depends_on:
      db:
        condition: service_healthy
      ldap:
        condition: service_healthy
    restart: unless-stopped
    # NOTE: The 'arc' image itself doesn't have a simple TCP healthcheck defined here,
    #       it relies on internal Wildfly status. Docker compose reports it unhealthy if startup fails.

  # PostgreSQL Database for Archive
  db:
    image: postgres:15-alpine # Use a specific version of postgres
    container_name: dcm4chee_db_test # Optional
    environment:
      - POSTGRES_DB=pacsdb
      - POSTGRES_USER=pacs
      - POSTGRES_PASSWORD=pacs
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pacs -d pacsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # OpenLDAP for Archive Configuration
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.7-33.1
    container_name: dcm4chee_ldap_test # Optional
    environment:
      - LDAP_ROOTPASS=secret
      - LDAP_CONFIG_PASSWORD=secret # Usually needed as well
    volumes:
      - ldap_config:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    healthcheck:
      # Basic check: See if the LDAP port is responding
      test: ["CMD", "ldapsearch", "-H", "ldap://localhost:389", "-x", "-b", ""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give LDAP some time to start before checking
    restart: unless-stopped

volumes:
  orthanc_db:
  postgres_db: # Volume for PostgreSQL data
  ldap_config: # Volume for LDAP config
  ldap_data:   # Volume for LDAP data