name: Nmap DICOM Test Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-nmap-dicom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dicom_server:
          - name: orthanc
            host_port: 11112
            service_name: orthanc
            compose_services: "orthanc" # Service(s) to start for this job
            # nmap_args: ""
          - name: dcm4chee-arc # Updated name for clarity
            host_port: 11113
            service_name: arc # Main service to test
            compose_services: "ldap db arc" # Start all required services
            # Default AE Title for dcm4chee-arc is often DCM4CHEE_ARC
            nmap_args: "--script-args dicom.called_aet=DCM4CHEE_ARC,dicom.calling_aet=ECHOSCU"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            nmap \
            tcpdump \
            tshark \
            docker-compose \
            netcat-openbsd \
            ldap-utils # Needed for ldapsearch in healthcheck

      - name: Copy custom Nmap files
        # (This step remains the same)
        run: |
          NMAP_SCRIPT_SRC="scripts/dicom-ping.nse"
          NMAP_LIB_SRC="nselib/dicom.lua"
          NMAP_DEFAULT_PATH="/usr/share/nmap"
          echo "Checking for Nmap script at: $PWD/$NMAP_SCRIPT_SRC"
          [ -f "$NMAP_SCRIPT_SRC" ] || { echo "::error::Nmap script file not found at '$PWD/$NMAP_SCRIPT_SRC'."; exit 1; }
          echo "Checking for Nmap library at: $PWD/$NMAP_LIB_SRC"
          [ -f "$NMAP_LIB_SRC" ] || { echo "::error::Nmap library file not found at '$PWD/$NMAP_LIB_SRC'."; exit 1; }
          echo "Using standard Nmap path: $NMAP_DEFAULT_PATH"
          echo "Copying Nmap script and library..."
          sudo mkdir -p "${NMAP_DEFAULT_PATH}/scripts/" "${NMAP_DEFAULT_PATH}/nselib/"
          sudo cp "$NMAP_SCRIPT_SRC" "${NMAP_DEFAULT_PATH}/scripts/"
          sudo cp "$NMAP_LIB_SRC" "${NMAP_DEFAULT_PATH}/nselib/"
          echo "Updating Nmap script database..."
          sudo nmap --script-updatedb
          echo "Nmap script database updated."

      - name: Start DICOM Server Stack (${{ matrix.dicom_server.name }})
        run: |
          echo "Starting Docker services: ${{ matrix.dicom_server.compose_services }}"
          # Use --wait if possible and healthchecks are reliable, otherwise increase sleep
          # docker-compose up -d --remove-orphans --wait ${{ matrix.dicom_server.compose_services }}
          # Falling back to sleep for broader compatibility
          docker-compose up -d --remove-orphans ${{ matrix.dicom_server.compose_services }}
          UP_EXIT_CODE=$?

          if [ $UP_EXIT_CODE -ne 0 ]; then
            echo "::error::'docker-compose up' failed with exit code $UP_EXIT_CODE. Dumping logs:"
            docker-compose logs || echo "Failed to get logs after compose up failure." # Log all services on failure
            exit $UP_EXIT_CODE
          fi

          # Increased wait time as dcm4chee-arc stack takes time
          WAIT_TIME=90
          echo "Waiting ${WAIT_TIME}s for ${{ matrix.dicom_server.service_name }} stack to initialize..."
          sleep ${WAIT_TIME}

          echo "Checking if port ${{ matrix.dicom_server.host_port }} is listening..."
          if ! nc -z -v localhost ${{ matrix.dicom_server.host_port }}; then
            echo "::error::Port ${{ matrix.dicom_server.host_port }} is not open after wait. Dumping logs:"
            docker-compose logs || echo "Failed to get logs after port check failure."
            echo "Docker container status:"
            docker ps -a
            exit 1
          else
            echo "Port ${{ matrix.dicom_server.host_port }} is open. Proceeding with test."
          fi

      - name: Start tcpdump capture (${{ matrix.dicom_server.name }})
        # (This step remains the same)
        id: start_tcpdump
        run: |
          TARGET_PORT=${{ matrix.dicom_server.host_port }}
          PCAP_FILE="dicom_capture_${{ matrix.dicom_server.name }}.pcap"
          echo "Starting tcpdump capture for port $TARGET_PORT..."
          sudo tcpdump -i any -s 0 "port $TARGET_PORT" -w "$PCAP_FILE" &
          echo "tcpdump_pid=$!" >> $GITHUB_OUTPUT
          echo "pcap_file=$PCAP_FILE" >> $GITHUB_OUTPUT
          echo "Tcpdump started (PID: $!), capturing to $PCAP_FILE"

      - name: Run Nmap Test (${{ matrix.dicom_server.name }})
        # (This step remains the same - uses nmap_args from matrix)
        id: test_script
        run: |
          echo "--- Testing ${{ matrix.dicom_server.name }} DICOM server on host port ${{ matrix.dicom_server.host_port }} ---"
          nmap -p ${{ matrix.dicom_server.host_port }} \
               -d \
               --script="dicom-ping.nse" \
               ${{ matrix.dicom_server.nmap_args || '' }} \
               --script-trace \
               localhost || { echo "::error::Nmap command failed for ${{ matrix.dicom_server.name }}"; exit 1; }

      - name: Show Server Logs (${{ matrix.dicom_server.name }})
        # (This step remains the same)
        if: always()
        run: |
          echo "--- ${{ matrix.dicom_server.name }} server logs (Tail) ---"
          docker-compose logs --tail="50" ${{ matrix.dicom_server.service_name }} || echo "Failed to get logs for ${{ matrix.dicom_server.service_name }}."
          echo "--- ${{ matrix.dicom_server.name }} server logs (DICOM Filter) ---"
          docker-compose logs ${{ matrix.dicom_server.service_name }} | grep -A 5 -B 5 -E "DICOM|DIMSE|Association" || echo "No relevant mentions found in ${{ matrix.dicom_server.name }} logs."

      - name: Stop tcpdump capture (${{ matrix.dicom_server.name }})
        # (This step remains the same)
        if: always()
        run: |
          TCPDUMP_PID="${{ steps.start_tcpdump.outputs.tcpdump_pid }}"
          echo "Attempting to stop tcpdump (PID: $TCPDUMP_PID) for ${{ matrix.dicom_server.name }}..."
          if [ -n "$TCPDUMP_PID" ]; then
             sudo kill "$TCPDUMP_PID" 2>/dev/null || echo "tcpdump already stopped or signal failed."
             sleep 2
             sudo kill -0 "$TCPDUMP_PID" 2>/dev/null && sudo kill -9 "$TCPDUMP_PID" || echo "tcpdump cleanly stopped or already gone."
           else
             echo "tcpdump PID not found."
           fi
           sleep 2

      - name: Print PCAP Info (${{ matrix.dicom_server.name }})
       # (This step remains the same)
        if: always()
        run: |
          PCAP_FILE="${{ steps.start_tcpdump.outputs.pcap_file }}"
          echo "Checking PCAP file: $PCAP_FILE"
          if [[ -f "$PCAP_FILE" && -s "$PCAP_FILE" ]]; then
            echo "--- PCAP Info for $PCAP_FILE ---"
            tshark -r "$PCAP_FILE" -c 100 -Y dicom || echo "No DICOM packets found or tshark error."
            echo "--- End PCAP Info ---"
          elif [[ -f "$PCAP_FILE" ]]; then
             echo "PCAP file $PCAP_FILE exists but is empty."
          else
            echo "PCAP file $PCAP_FILE not found."
          fi
        continue-on-error: true

      - name: Upload pcap artifact (${{ matrix.dicom_server.name }})
        # (This step remains the same)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dicom-pcap-${{ matrix.dicom_server.name }}
          path: ${{ steps.start_tcpdump.outputs.pcap_file }}
          if-no-files-found: ignore

      # Cleanup: Stop ALL services defined in the compose file at the end of each job
      #          This is simpler than stopping only specific ones if state isn't needed.
      - name: Stop DICOM Server Stack (${{ matrix.dicom_server.name }})
        if: always()
        run: |
          echo "Stopping all docker services..."
          docker-compose down --volumes --remove-orphans # Bring everything down cleanly