name: Nmap DICOM Test (using test_nmap.sh)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-nmap-dicom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: Keep the diagnostic step for future debugging if needed, or remove it.
      - name: List files after checkout (Diagnostic)
        run: |
          echo "Current directory: $PWD"
          echo "Listing root directory contents:"
          ls -la .

      - name: Set up Python # Optional
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            nmap \
            tcpdump \
            tshark \
            docker-compose

      - name: Copy custom Nmap files
        run: |
            # --- Paths based on ls output ---
            NMAP_SCRIPT_SRC="scripts/dicom-ping.nse"
            NMAP_LIB_SRC="nselib/dicom.lua"

            echo "Checking for Nmap script at: $PWD/$NMAP_SCRIPT_SRC"
            if [ ! -f "$NMAP_SCRIPT_SRC" ]; then
            echo "::error::Nmap script file not found at '$PWD/$NMAP_SCRIPT_SRC'."
            exit 1
            fi

            echo "Checking for Nmap library at: $PWD/$NMAP_LIB_SRC"
            if [ ! -f "$NMAP_LIB_SRC" ]; then
            echo "::error::Nmap library file not found at '$PWD/$NMAP_LIB_SRC'."
            exit 1
            fi

            # --- Use standard hardcoded Nmap path ---
            NMAP_DEFAULT_PATH="/usr/share/nmap"
            echo "Using standard Nmap path: $NMAP_DEFAULT_PATH"

            echo "Copying Nmap script and library..."
            # Use the standard path directly in commands
            sudo mkdir -p "${NMAP_DEFAULT_PATH}/scripts/"
            sudo mkdir -p "${NMAP_DEFAULT_PATH}/nselib/"
            sudo cp "$NMAP_SCRIPT_SRC" "${NMAP_DEFAULT_PATH}/scripts/"
            sudo cp "$NMAP_LIB_SRC" "${NMAP_DEFAULT_PATH}/nselib/"

            echo "Updating Nmap script database..."
            # This command should still work
            sudo nmap --script-updatedb
            echo "Nmap script database updated."

      - name: Start tcpdump capture
        id: start_tcpdump
        run: |
          DICOM_PORT=11112
          echo "Starting tcpdump capture for port $DICOM_PORT..."
          sudo tcpdump -i any -s 0 port $DICOM_PORT -w dicom_capture_orthanc.pcap &
          echo "tcpdump_pid=$!" >> $GITHUB_OUTPUT

      - name: Make test script executable
        # Script is at the root level now
        run: chmod +x test_nmap.sh # NO nmap_dicom/ prefix

      - name: Run DICOM Test Script
        id: test_script
        # REMOVED working-directory line, run from repo root
        run: |
          # Execute script from repo root
          bash ./test_nmap.sh # Use bash explicitly or ./

      # --- Rest of the steps remain the same ---
      - name: Stop tcpdump capture
        if: always()
        run: |
          echo "Stopping tcpdump (PID: ${{ steps.start_tcpdump.outputs.tcpdump_pid }})..."
          if [ -n "${{ steps.start_tcpdump.outputs.tcpdump_pid }}" ]; then
            sudo kill ${{ steps.start_tcpdump.outputs.tcpdump_pid }} || echo "tcpdump already stopped or kill signal failed."
            sleep 2
            sudo kill -0 ${{ steps.start_tcpdump.outputs.tcpdump_pid }} 2>/dev/null && sudo kill -9 ${{ steps.start_tcpdump.outputs.tcpdump_pid }} || echo "tcpdump cleanly stopped or already gone."
          else
            echo "tcpdump PID not found in step outputs. Capture might not have started correctly."
          fi
          sleep 2

      - name: Print PCAP Info
        if: always()
        run: |
          PCAP_FILE="dicom_capture_orthanc.pcap"
          if [[ -f "$PCAP_FILE" ]]; then
            echo "--- PCAP Info for $PCAP_FILE ---"
            tshark -r "$PCAP_FILE" -c 50 -Y dicom || echo "No DICOM packets found or tshark error."
            echo "--- End PCAP Info ---"
          else
            echo "PCAP file $PCAP_FILE not found."
          fi
        continue-on-error: true

      - name: Upload pcap artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dicom-pcap-capture-orthanc
          path: dicom_capture_orthanc.pcap
          if-no-files-found: ignore

      - name: Check test script outcome
        if: steps.test_script.outcome != 'success'
        run: |
          echo "::error::Test script 'test_nmap.sh' failed!"
          exit 1