name: Rust DICOM Ping (Nmap)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-dicom-ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Small tools only (Docker already available on hosted runner)
      - name: Install tools
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y nmap netcat-openbsd iproute2 lsof

      - name: Install custom Nmap dicom-ping + nselib
        run: |
          set -eux
          sudo mkdir -p /usr/share/nmap/scripts /usr/share/nmap/nselib
          sudo cp scripts/dicom-ping.nse /usr/share/nmap/scripts/
          sudo cp nselib/dicom.lua       /usr/share/nmap/nselib/
          sudo nmap --script-updatedb

      - name: Start Orthanc upstream (DIMSE 4242)
        run: |
          set -eux
          docker run -d --rm --name orthanc_up \
            -p 4242:4242 -p 8042:8042 \
            -e ORTHANC__REMOTE_ACCESS_ALLOWED=true \
            orthancteam/orthanc:latest
          # Wait until Orthanc DIMSE is accepting connections
          for i in {1..60}; do
            if nc -z 127.0.0.1 4242; then
              echo "Orthanc DIMSE is up"
              break
            fi
            sleep 1
          done
          nc -z 127.0.0.1 4242

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install dicom-scpproxy
        run: |
          set -eux
          cargo install --locked dicom-scpproxy
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Start Rust DIMSE SCP (dicom-scpproxy on 11116)
        run: |
          set -eux
          export PATH="$HOME/.cargo/bin:$PATH"

          echo "Starting dicom-scpproxy..."
          # small delay so Orthanc is definitely ready
          sleep 5

          # v0.9.0 syntax: dicom-scpproxy --listen-port <port> <dest-host> <dest-port>
          # Enable raw SNAFU errors so our NSE early-close matcher sees exact strings.
          SNAFU_RAW_ERROR_MESSAGES=1 \
          dicom-scpproxy \
            --listen-port 11116 \
            127.0.0.1 \
            4242 \
            > scpproxy.log 2>&1 &
          echo $! > scpproxy.pid

          echo "Waiting for dicom-scpproxy to bind port 11116..."
          for i in {1..60}; do
            if ss -ltn | grep -q ':11116'; then
              echo "dicom-scpproxy is listening on 11116"
              break
            fi
            sleep 1
          done

          if ! ss -ltn | grep -q ':11116'; then
            echo "dicom-scpproxy failed to start. Log output follows:"
            cat scpproxy.log || true
            exit 1
          fi

      - name: Debug scpproxy log and sockets
        if: always()
        run: |
          echo "---- dicom-scpproxy.log ----"
          cat scpproxy.log || echo "(no log file)"
          echo "---- Listening sockets ----"
          ss -ltn

      - name: Nmap ping against Rust DIMSE (11116)
        id: nmap_ping
        env:
          NMAPDIR: /usr/share/nmap
        run: |
          set -euxo pipefail
          OUT="nmap_rust_dicom_ping.txt"
          DBG="nmap_debug.txt"

          # Force our script to run on 11116 and keep it fast/bounded.
          nmap -Pn -n -p 11116 \
            --max-retries 0 \
            --host-timeout 45s \
            --script-timeout 20s \
            --script dicom-ping \
            --script-args dicom-ping.ports=11116,dicom.called_aet=ORTHANC \
            localhost -d2 --script-trace 2> "$DBG" | tee "$OUT"

          echo "out=$OUT" >> "$GITHUB_OUTPUT"
          echo "dbg=$DBG" >> "$GITHUB_OUTPUT"

      - name: Assert output (must show early-close discovery on 11116)
        run: |
          set -e
          OUT="${{ steps.nmap_ping.outputs.out }}"
          DBG="${{ steps.nmap_ping.outputs.dbg }}"

          # Must at least discover the DICOM service
          if ! grep -q 'DICOM Service Provider discovered' "$OUT"; then
            echo "::error::DICOM service not discovered on Rust port 11116"
            echo "---- Nmap STDOUT ----"; cat "$OUT" || true
            echo "---- Nmap NSE debug ----"; tail -n +1 "$DBG" || true
            exit 1
          fi

          # Specifically require the early-close config line for this target
          if ! grep -q 'Association ended early by peer' "$OUT"; then
            echo "::error::Expected 'Association ended early by peer' on port 11116 but did not find it."
            echo "---- Nmap STDOUT ----"; cat "$OUT" || true
            echo "---- Nmap NSE debug ----"; tail -n +1 "$DBG" || true
            exit 1
          fi

          echo "✔ Rust DIMSE discovered and early-close behavior confirmed on 11116."

      - name: Nmap sanity check against Orthanc (4242)
        if: always()
        env:
          NMAPDIR: /usr/share/nmap
        run: |
          nmap -Pn -n -p 4242 \
            --max-retries 0 \
            --host-timeout 30s \
            --script-timeout 15s \
            --script dicom-ping \
            --script-args dicom.called_aet=ORTHANC \
            localhost | tee nmap_orthanc_check.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rust-dicom-ping-artifacts
          path: |
            scpproxy.log
            ${{ steps.nmap_ping.outputs.out }}
            ${{ steps.nmap_ping.outputs.dbg }}
            nmap_orthanc_check.txt

      - name: Cleanup
        if: always()
        run: |
          set -eux
          if [ -f scpproxy.pid ]; then
            kill "$(cat scpproxy.pid)" || true
          fi
          docker stop orthanc_up || true
